name: Publish Nuget Package

on:
  push:
    tags: [ '*.*.*' ]
  workflow_dispatch:
  
env:
  BUILD_CONFIGURATION:  'Release'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
          
      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Pack
        run:  |
              dotnet pack -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'
          
      - name: Upload Package to nuget.org
        uses: tedd/publish-nuget-neo@v1.0.2
        with:
          NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
          INCLUDE_SYMBOLS: true
