name: Publish Nuget Package

on:
  push:
    tags: [ '*.*.*' ]
  workflow_dispatch:
  
env:
  BUILD_CONFIGURATION:  'Release'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Authenticate with Github Packages
        run:  |
              dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name VirtualButton "https://nuget.pkg.github.com/radj307/index.json"
              
      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Pack
        run:  |
              dotnet pack -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: '${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg'

      - name: Publish Package to Github Packages
        run:  |
              $dir="${{ github.workspace }}/bin/${{ env.BUILD_CONFIGURATION }}"
              $file=[System.IO.Path]::GetRelativePath($dir, $($(Get-ChildItem -Path "$dir" -File) -like '*.nupkg'))
              dotnet nuget push "$file" --api-key '${{ secrets.GHP_PAT }}' --source "github"
          
      - name: Upload Package to nuget.org
        uses: tedd/publish-nuget-neo@v1.0.2
        with:
          NUGET_KEY:  '${{ secrets.NUGET_API_KEY }}'
          INCLUDE_SYMBOLS: true
